export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SEARCH = 'GET_PRODUCTS_SEARCH';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_SEARCH_FAIL = 'GET_PRODUCTS_SEARCH_FAIL';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const SET_PRODUCT_PAGE = 'SET_PRODUCT_PAGE';

export const CART_LOADED_SUCCESS = 'CART_LOADED_SUCCESS';
export const CART_LOADED_FAIL = 'CART_LOADED_FAIL';

export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const DELETE_PRODUCT_CART_SUCCESS = 'DELETE_PRODUCT_CART_SUCCESS';
export const DELETE_PRODUCT_CART_FAIL = 'DELETE_PRODUCT_CART_FAIL';

export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';

export const AUTH_LOADING = 'AUTH_LOADING';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const CART_LOADING = 'CART_LOADING';
